language: node_js
node_js: 8
script: npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: UMYCcsq4LSDwlvKPMEAFl+TgqBf0P+0QnytwrOQkBwKKfrWIAXy/OgEY6c+RerPf2K6CKO0x4tohKvdykdaMLYx27+n2iPa+HAVUJruMZvZaIT2tS6a9tJIhHCFcxmXYSDSk732B1KX66/bG4tiAx2n2gNzdqQGvcMFqwXzJxua9fk7Iwlz5yl5MVtFbhmVa2n3u3OXS47wXeG4pNqTj2kdWYwY28qkxHwF7ctPkFs6LNg0WSku0Iokx60fQtEoaCSl5xts65G+tUE0TKQiDS+qk0tYCHEp6zXyMg9J0YxlOQ0WMVj5hof/L4rtbAbGH595MiQw/h/+GUm1MCufODM0e06K5IDAecvSsQVGe4L5Z0VuhgUyhDi6Fm3VCx5JPNHvaJf7Tp2D7W/SUrOTlM3JtjsG27UfHdUvehdM9ZAztPUib8iuc7lOT5DVunV0e0LKbiRRHpsZrFQb+rDY7MMWIpQs+XaGs0n6ew513J/dUJDGLjgDn//dvKYGYg/cN+SYLfUVWxd1Ftg9HSWyy3WaWDB/ae5Erl0LQ2KTyOjtJw6D0AwlBpRu4okZPzKT4n+BvzjaTf2smnvcNUmN1lpV7q2UKHdLf7nWz+/ta/xgzKgLQ7Mu7mL89khVNcQppWYQNrEZiZSS5U+FaJ1S99961JUAj0XxnVEwnyGqjWog=